ERROR: line 3: Function 'foo' is already exist
